### ISSUE TITLE
how to use server power.on operation

### ISSUE THREAD

**Issue by liyang2018** [cloudify-incubator/cloudify-utilities-plugin#109]
Can someone tell me how to executions cloudify.interfaces.power.on operation? i git clone this project, and then some of the functions are added. But I don't know how to start (using cloudify.interfaces.power.on) an existing server by using blueprint.yaml.
If you can give me the direction, I'll be grateful

**Comment by 0lvin** [comment]
You can use `execute_operation` workflow: https://docs.cloudify.co/4.3.0/working_with/workflows/built-in-workflows/#the-execute-operation-workflow

Like example:

```bash
cfy executions start execute_operation -p operation=cloudify.interfaces.lifecycle.reboot -p node_instance_ids=['qemu_vm_t3qrow'] -b examples
```
