### ISSUE TITLE
Rest Plugin: support error code as accepted.

### ISSUE THREAD

**Issue by 0lvin** [cloudify-incubator/cloudify-utilities-plugin#184]
Support RestApi where error code is expected for success [operation](https://github.com/cloudify-incubator/cloudify-utilities-plugins-sdk/blob/0.0.10/cloudify_rest_sdk/utility.py#L179).

**Comment by arikyakir** [comment]
Thanks denis!

**Comment by 0lvin** [comment]
Implemented in [1.15.3](c720f9c385a785b8905991465fb74c75fca42220)
