### ISSUE TITLE
Provide Example Blueprints for Terminal Feature

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-utilities-plugin#41]

**Comment by 0lvin** [comment]
We have such examples in repository:
[Cisco](https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/master/cloudify_terminal/example/cisco.yaml) - show currently assigned ip's
[Fortigate](https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/master/cloudify_terminal/example/fortigate.yaml) -  show assigned ip's and raise error(for show possible error detect settings)
[Simple ssh to linux vm](https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/master/cloudify_terminal/example/linux-ssh.yaml) - run hostname on vm

**Comment by EarthmanT** [comment]
released in 1.2.5
