### ISSUE TITLE
DeploymentProxy: execute_start and timeout

### ISSUE THREAD

**Issue by isaac-s** [cloudify-incubator/cloudify-utilities-plugin#72]
Two issues:

1. The `timeout` operation input for `start` is very important, but is not documented in `plugin.yaml`. Users need to read the code in order to know that the execution timeout is configurable.

2. Request from customer: allow for an infinite timeout (no timeout). This is currently not supported because `poll_with_timeout` assumes that `timeout` is a positive integer. Can we perhaps support `-1` as infinity?

**Comment by EarthmanT** [comment]
#73 @isaac-s
