### ISSUE TITLE
Spin loop & hammering manager when redirecting logs

### ISSUE THREAD

**Issue by isaac-s** [cloudify-incubator/cloudify-utilities-plugin#74]
https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/1.4.3/cloudify_deployment_proxy/polling.py#L86

This function is incorrect and causes:

* Spin loops accompanied by endless REST requests to the manager
* Hang when polling

The way the function is implemented, if we enter the function, issue `client.events.get` and both of these conditions are true:

* Less than 100 events are returned
* The execution actually finished

— Then we'll be stuck in a loop forever, and this loop will hammer the manager with `events list` requests.

**Comment by 0lvin** [comment]
loop must be stopped when value in:
```python
last_event = int(ctx.instance.runtime_properties[COUNT_EVENTS].get(execution_id, 0))
``` 
equal or bigger to second value from 

```events, full_count =  _client.events.get()```
