### ISSUE TITLE
Add Support For NonRecoverableError response flag in rest plugin

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-utilities-plugin#90]
We're missing very important feature in REST Plugin - which is support for "nonrecoverable_response". We need to have a way to capture responses which should not be recoverable and workflow should just stop.
Sample template with nonrecoverable response support:

rest_calls:
  - path: /posts
    method: GET
    headers:
      Content-type: application/json
    payload:
    response_format: json
    recoverable_codes: [400]
    nonrecoverable_response:
      - ["response", "success"]
    response_expectation:
      - ["author", "John"]
    response_translation:

**Comment by astianseb** [comment]
Template in initial email got bit messed up, so I'll recycle it again:
`
rest_calls:
  - path: /posts
    method: GET
    headers:
      Content-type: application/json
    payload:
    response_format: json
    recoverable_codes: [400]
    nonrecoverable_response:
      - ["response", "success"]
    response_expectation:
      - ["author", "John"]
    response_translation:
`
